# --- !Ups

-- CREATE TABLE DISHES (
--   DISH_ID   BIGSERIAL,
--   DISH_NAME VARCHAR,
--   CODE      VARCHAR,
--   WEIGTH    INT,
--   CALORIES  VARCHAR,
--   PROTEINS  INT,
--   CARBS     INT,
--   FAT       INT,
--   PRICE     VARCHAR,
--   PRIMARY KEY (DISH_ID)
-- );

/*CREATE TABLE DISH_SCORES (
  USERNAME VARCHAR NOT NULL,
  DISH_ID  BIGINT  NOT NULL,
  VALUE    REAL    NOT NULL,
  PRIMARY KEY (USERNAME, DISH_ID)
--  FOREIGN KEY (DISH_ID) REFERENCES DISHES(DISH_ID)
); */

CREATE TABLE USERS (
  USER_ID  BIGSERIAL,
  USERNAME VARCHAR NOT NULL,
  PASSWORD VARCHAR NOT NULL,
  PRIMARY KEY (USER_ID)
);


# --- !Downs

/*DROP TABLE DISHES;
DROP TABLE DISH_SCORES;
DROP TABLE USERS;*/
